# Generated by Django 3.0.8 on 2020-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockperformance',
            name='read_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blockperformance',
            name='write_speed',
            field=models.IntegerField(),
        ),
    ]
