# Generated by Django 3.0.8 on 2020-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio_chart', '0002_auto_20200801_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebenchmark',
            name='drive_fw',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
