# Generated by Django 3.0.8 on 2020-08-02 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fio_chart', '0003_drivebenchmark_drive_fw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivebenchmark',
            options={'ordering': ['modified']},
        ),
        migrations.AddField(
            model_name='drivebenchmark',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
